homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
  
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Zones
zone:
  - name: Gym
    latitude: !secret gym_lat
    longitude: !secret gym_long
    radius: 200

  - name: Grocery
    latitude: !secret grocery_lat
    longitude: !secret grocery_long
    radius: 200
    
  - name: School
    latitude: !secret nrg_lat
    longitude: !secret nrg_long
    radius: 200
    
  - name: !secret jwork_name
    latitude: !secret jwork_lat
    longitude: !secret jwork_long
    radius: 250
  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#   base_url: example.duckdns.org:8123
http:
# Discover some devices automatically
#discovery:

#Shopping List Temp
shopping_list:

#Included Config Files
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

##############################################################################

#Alarm Config
alarm_control_panel:
  - platform: manual
    name: Home Alarm
#    code: !secret alarm_code
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_custom_bypass:
      pending_time: 30
      delay_time: 20


##############################################################################

# Sensors
sensor:

##Arlo
  - platform: arlo
    monitored_conditions:
      - captured_today
      - last_capture
      - total_cameras
      - battery_level
      - signal_strength

## Griddy LIVE POWER PRICING
  - platform: rest
    name: griddy
    resource: https://app.gogriddy.com/api/v1/insights/getnow
    method: POST
    payload: !secret griddy_json
    value_template: '{{ value_json["now"]["price_ckwh"] }}'
    unit_of_measurement: "¢/kwh"

##SERVER STATUS
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: memory_free
      - type: load_1m
      - type: load_5m
      - type: processor_use
      - type: network_in
        arg: eno1
      - type: network_out
        arg: eno1
      - type: last_boot

##UPS Status
  - platform : rest 
    resource: http://192.168.1.205:5002/pwrstat 
    name: Battery Backup 
    value_template: '{{ value_json["State"] }}' 
    json_attributes:  
    - Remaining Runtime 
    - Load 
    - Power Supply by 
    - Last Power Event 
    - Test Result 
    - Utility Voltage 
    - Line Interaction 
    - Battery Capacity 

##Have i been pwnd
  - platform: haveibeenpwned
    email: 
    - !secret mail_user
    - !secret home_mail_user

## Zillow
  - platform: zestimate
    api_key: !secret zillow_api
    zpid: !secret zillow_pid

##Unifi USG Status
  - platform: unifigateway
    host: 192.168.1.202
    username: !secret unifi_user
    password: !secret unifi_pass
    monitored_conditions:
      - www
      - wlan
      - alerts
      - firmware
      - wan

##KONNECTED
konnected:
  access_token: !secret konnected_token
  devices:
    - id: bcddc29d2bae
      binary_sensors:
        - zone: 1
          type: door
          name: 'Front Door'
        - zone: 2
          type: door
          name: 'Garage Entry'
        - zone: 3
          type: door
          name: 'Back Door'
        - zone: 4
          type: motion
          name: 'Living Room Motion'
        - zone: 5
          type: door
          name: 'Windows'
        - zone: 6
          type: door
          name: 'Windows 2'
      switches:
        - zone: out
          name: siren

####UNIFI DEVICE TRACKER###
device_tracker: 
  - platform: unifi_direct
    host: 192.168.1.254
    username: admin
    password: !secret unifiAP_key
    consider_home: 300
    new_device_defaults:
      track_new_devices: true
  - platform: google_maps
    username: !secret home_mail_user
    password: !secret home_mail_pass
    
############################################
    ##DEVICES##
#Lyric    
#climate:
#  - platform: honeywell
#    username: !secret mail_user
#    password: !secret lyric_pass
#    region: us
#    scan_interval: 600
    
# ZWave    
zwave:
  usb_path: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_6120128A-if00-port0
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_network_key


#######################################################################

# Text to speech
tts:
  - platform: google_translate


# MEDIA
wake_on_lan: # enables `wake_on_lan` domain

media_player:
  - platform: webostv
    host: 192.168.1.212
    name: Family Room TV
    filename: webostv.conf
    timeout: 5
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "A8:23:FE:79:E3:9E"
    customize:
      sources:
      
#  - platform: plex      
roku:
    - host: 192.168.1.220
################################################################################
#Cloud Platforms
rachio:
  api_key: !secret rachio_api_key

arlo:
  username: !secret home_mail_user
  password: !secret arlo_key
  
lyric:
  client_id: !secret lyric_client_key
  client_secret: !secret lyric_client_secret
  
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    
ifttt:
   key: !secret ifttt_api_key
   
sense:
  email: !secret home_mail_user
  password: !secret sense_pass

# Calandar  
google:
  client_id: !secret homecalandar_client
  client_secret: !secret homecalandar_key
  
##############################################################################
#VISUAL INTERFACES
panel_iframe:
  rachio:
    title: Rachio
    url: "https://app.rach.io"
    icon: mdi:water-pump
frontend:
    themes: !include themes.yaml


usps_mail:
  provider: gmail
  email: !secret mail_user
  password: !secret mail_pass
  camera: true
  default_image: /www/nomail.png

#Utility Meter  
utility_meter:
  energy:
    source: sensor.energy_usage
    cycle: monthly
    offset:
      days: 17

logger:
  default: warn
  logs:
    custom_components.usps_mail: debug
    
#HACS
hacs:
  token: !secret github_key
    #alarm_control_panel: !include alarm.yaml
#panel_custom: !include panel_custom.yaml
